# Generated by Django 4.0.3 on 2022-03-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=50, null=True)),
                ('time_login', models.BigIntegerField(null=True)),
                ('time_wrong_pwd', models.BigIntegerField(null=True)),
                ('num_wrong_pwd', models.IntegerField(null=True)),
            ],
        ),
    ]
