# Generated by Django 4.0.3 on 2022-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=10)),
                ('storetype_id', models.CharField(max_length=10)),
                ('store_size', models.IntegerField()),
                ('city_id', models.CharField(max_length=10)),
            ],
        ),
    ]
