# Generated by Django 4.0.3 on 2022-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
