# Generated by Django 4.0.3 on 2022-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reading_prod', models.BooleanField(default=False)),
                ('is_reading_sale', models.BooleanField(default=False)),
                ('is_reading_store', models.BooleanField(default=False)),
            ],
        ),
    ]
