# Generated by Django 4.0.3 on 2022-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='time_read_prod',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='time_read_sale',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='time_read_store',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
