# Generated by Django 4.0.3 on 2022-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('store_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('sales', models.DecimalField(decimal_places=1, max_digits=15)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.DecimalField(decimal_places=1, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('promo_type_1', models.CharField(max_length=10, null=True)),
                ('promo_bin_1', models.CharField(max_length=10, null=True)),
                ('promo_type_2', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
