# Generated by Django 4.0.3 on 2022-03-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='promo_bin_1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='promo_type_1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='promo_type_2',
        ),
    ]
