# Generated by Django 4.0.3 on 2022-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_length', models.DecimalField(decimal_places=1, max_digits=6)),
                ('product_width', models.DecimalField(decimal_places=1, max_digits=6)),
                ('product_depth', models.DecimalField(decimal_places=1, max_digits=6)),
                ('cluster_id', models.CharField(max_length=10, null=True)),
                ('hierarchy1_id', models.CharField(max_length=10)),
                ('hierarchy2_id', models.CharField(max_length=12)),
                ('hierarchy3_id', models.CharField(max_length=15)),
                ('hierarchy4_id', models.CharField(max_length=18)),
                ('hierarchy5_id', models.CharField(max_length=20)),
            ],
        ),
    ]
